version: '1'

volumes:
  volume-data:

services:
  mysql:
    image: 'mysql:8.0.29'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=appDb
    volumes:
      - volume-data:/var/lib/mysql
